import { expect, test, ui } from '../lib/test.ts';
import type { Actor, Actors } from '../lib/actors.ts';
const chips = (actor: Actor) => actor.page.locator('[data-presence-client]');
async function setup(actors: Actors, baseUrl: string, solo = false) {
  const principal = await actors.principal('ada');
  const ada = await actors.open(principal);
  const response = await ada.context.request.post('/api/docs', { headers: { Origin: baseUrl }, data: { title: 'Presence', markdown: 'A shared paragraph for our cursors.' } });
  expect(response.status()).toBe(201);
  const { doc: { id } } = await response.json();
  await ada.goto(`/d/${id}`);
  await expect(ui.body(ada, id)).toHaveAttribute('data-body-binding', 'live');
  await expect(chips(ada)).toHaveCount(0);
  const second = solo ? principal : await actors.principal('ben');
  if (!solo) expect((await ada.context.request.post(`/api/docs/${id}/members`, { headers: { Origin: baseUrl }, data: { email: second.email, role: 'editor' } })).ok()).toBe(true);
  const ben = await actors.open(second, { label: 'ben', path: `/d/${id}`, severable: true });
  await expect(ui.body(ben, id)).toHaveAttribute('data-body-binding', 'live');
  await expect(chips(ada)).toHaveCount(1);
  await expect(chips(ben)).toHaveCount(1);
  return { ada, ben, id };
}
test('j01 presence: three clients have stable distinct colors, matching carets and selections, typing labels and prompt leave @p:col-2 @evidence', async ({ actors, stack }) => {
  const { ada, ben, id } = await setup(actors, stack.baseUrl);
  const benColor = await chips(ada).getAttribute('data-presence-color');
  const caraPrincipal = await actors.principal('cara');
  expect((await ada.context.request.post(`/api/docs/${id}/members`, { headers: { Origin: stack.baseUrl }, data: { email: caraPrincipal.email, role: 'editor' } })).ok()).toBe(true);
  const cara = await actors.open(caraPrincipal, { path: `/d/${id}` });
  for (const actor of [ada, ben, cara]) await expect(chips(actor)).toHaveCount(2);
  await actors.requireDistinct(3);
  const colors = [...await chips(ada).evaluateAll(es => es.map(e => e.getAttribute('data-presence-color'))), await chips(ben).filter({ hasText: 'A' }).getAttribute('data-presence-color')];
  expect(new Set(colors).size).toBe(3);
  const peer = chips(ada).filter({ hasText: 'B' });
  await expect(peer).toHaveAttribute('data-presence-color', benColor!);
  await ui.body(ben, id).click();
  await ben.page.keyboard.press('End');
  const caret = ada.page.locator('[data-remote-caret]').filter({ has: ada.page.locator('[data-cursor-label]', { hasText: ben.principal!.name }) });
  await expect(caret).toBeVisible();
  const before = await caret.boundingBox();
  await ben.page.keyboard.press('ArrowLeft');
  await expect.poll(async () => (await caret.boundingBox())?.x, { timeout: 1000, intervals: [20] }).not.toBe(before?.x);
  await expect(caret).toHaveAttribute('data-presence-color', benColor!);
  await ben.page.keyboard.press('Shift+ArrowLeft');
  await expect(ada.page.locator('[data-remote-selection]')).toHaveAttribute('data-presence-color', benColor!);
  await ben.page.keyboard.press('ArrowRight');
  await ben.page.keyboard.type(' typing');
  await expect(caret.locator('[data-cursor-label]')).toBeVisible();
  await actors.checkpoint('signature-presence');
  await expect(caret.locator('[data-cursor-label]')).toBeHidden({ timeout: 3000 });
  await ben.goto('/');
  await expect(chips(ada)).toHaveCount(1, { timeout: 3000 });
});
test('j01 presence: a hard drop clears within 8–20 seconds @p:col-2', async ({ actors, stack }) => {
  const { ada, ben } = await setup(actors, stack.baseUrl);
  ben.expectReconnects(5);
  const at = Date.now(); ben.sever!.blackhole();
  await expect(chips(ada)).toHaveCount(0, { timeout: 20_000 });
  expect(Date.now() - at).toBeGreaterThanOrEqual(8000);
  ben.sever!.restore();
  await expect(chips(ada)).toHaveCount(1, { timeout: 20_000 });
});
test('j01 presence: one principal in two windows sees the other client and undo keeps peer text @p:col-1 @p:col-2 @p:col-3', async ({ actors, stack }) => {
  actors.solo('PRODUCT counts each window as a user; this leg deliberately shares a principal.');
  const { ada, ben, id } = await setup(actors, stack.baseUrl, true);
  await ui.body(ada, id).click(); await ada.page.keyboard.press('ControlOrMeta+End');
  await ada.page.keyboard.type(' Ada');
  await expect(ui.body(ben, id)).toContainText(' Ada');
  await ui.typeBody(ben, id, ' Ben');
  await expect(ui.body(ada, id)).toContainText(' Ben');
  await ui.body(ada, id).click(); await ada.page.keyboard.press('ControlOrMeta+z');
  await expect(ui.body(ada, id)).toContainText(' Ben');
  await expect(ui.body(ada, id)).not.toContainText(' Ada');
  await expect(ui.body(ben, id)).not.toContainText(' Ada');
});
